**tf.constant**

tf.constant(
    value, dtype=None, shape=None, name='Const'
)



In [2]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [2]:
matrix=tf.constant([[10.,7.,1.],[2.,3.,1.],[6.,9.,1.],[4.,6.,1.]],dtype=tf.float16 )

In [3]:
matrix

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[10.,  7.,  1.],
       [ 2.,  3.,  1.],
       [ 6.,  9.,  1.],
       [ 4.,  6.,  1.]], dtype=float16)>

In [4]:
matrix.ndim

2

In [6]:
tensor=tf.constant([[[1,2,3],[4,5,6]],
                    [[6,7,8],[9,10,11]],
                    [[12,13,14],[15,16,17]]])

In [8]:
tensor.ndim

3

**tf.variable**

tf.Variable(
    initial_value=None, trainable=None, validate_shape=True, caching_device=None,
    name=None, variable_def=None, dtype=None, import_scope=None, constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.compat.v1.VariableAggregation.NONE, shape=None
)


In [3]:
tensor_changed=tf.Variable([[1,2,3],[4,5,6]])

In [18]:
tensor_changed[0].assign([7,8,9])


<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[7, 8, 9],
       [4, 5, 6]])>

**tf.constant** are not changeable after declaration but **tf.Variable** are changeable

****random tensor**

In [20]:
random_tensor=tf.random.Generator.from_seed(7)
random_tensor=random_tensor.normal(shape=(3,2))
random_tensor_un=tf.random.Generator.from_seed(7)
random_tensor_un=random_tensor_un.uniform(shape=(3,2))
random_tensor,random_tensor_un

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.39932835, 0.7840713 ],
        [0.67880154, 0.73395896],
        [0.5520444 , 0.10948515]], dtype=float32)>)

**shuffling tensors** || so that neural network can learn throught different set of arrays.

In [21]:
not_shuffled=tf.constant([[4,5],[6,7],[7,8]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 7],
       [7, 8],
       [4, 5]])>

In [43]:
tf.random.set_seed(42)#global seed
tf.random.shuffle(not_shuffled,2)#operational seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [6, 7],
       [7, 8]])>

**tf.random.set_seed()** documentation

Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

*If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.

*If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.

*If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.

*If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [46]:
#tensors of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [48]:
#tensors of all zeros
tf.zeros(shape=(3,4)) 

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

**Tensors from Numpy Array**

Numpy array and Tensorflow tensors are almost similar. However Tensors can run on GPU but Numpy Array cant do that. 

In [49]:
import numpy as np
numpy_arr=np.arange(1,25,dtype=np.int32)
numpy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [51]:
tensor_from_numpy=tf.constant(numpy_arr)
tensor_from_numpy

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [70]:
tensor_from_numpy_1=tf.constant(numpy_arr,shape=(4,3,2))
tensor_from_numpy_1

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])>

**Ways to get info about tensor**  
*Shape*  ||
*dim*  ||
*size*


In [75]:
new_tensor=tf.zeros([2,3,3,4])
new_tensor

<tf.Tensor: shape=(2, 3, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [81]:
print("Shape of the tensor :",new_tensor.shape) 
print("Dimension of the tensor :",new_tensor.ndim)
print("Total elements in tensor :",tf.size(new_tensor).numpy())

Shape of the tensor : (2, 3, 3, 4)
Dimension of the tensor : 4
Total elements in tensor : 72


**Indexing Tensors** || **Expanding Tensor**

In [94]:
a=tf.random.Generator.from_seed(seed=7)
a=tf.random.normal(shape=(3,4))
a

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.0307604 ,  0.29017973,  1.2829775 ,  0.81271535],
       [-0.79449177,  0.20022836,  1.80325   , -1.0376493 ],
       [-1.2340679 , -1.2608271 ,  0.11458235,  0.11852823]],
      dtype=float32)>

In [96]:
a[:1]

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0.0307604 , 0.29017973, 1.2829775 , 0.81271535]], dtype=float32)>

In [112]:
arr=np.arange(1,10,dtype=np.int32)
arr_t=tf.constant(arr,shape=(3,3))
arr_t

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [115]:
expanded_arr_t=arr_t[...,tf.newaxis] # here ... means all the dimension in arr_t
expanded_arr_t

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])>

In [116]:
tf.expand_dims(arr_t,axis=-1) #here -1 means expand after the last axis of arr_t

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])>

**Tensor Operations**

In [7]:
ts1=tf.constant([[1,2],[3,4]])
ts1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [6]:
ts2=tf.constant([[4,5],[5,6]])
ts2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [5, 6]])>

In [8]:
tf.matmul(ts1,ts2) 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 17],
       [32, 39]])>

In [9]:
#python matrix multiplication
ts1@ts2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 17],
       [32, 39]])>

In [16]:
tf.tensordot(tf.transpose(ts1),tf.transpose(ts2),axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 23],
       [28, 34]])>

Changing datatype 

Chaning dtype from 32 bit precision to 16 bit precision can increase computation power in NVIDIA GPU. 

In [17]:
ts1=tf.cast(ts1,dtype=tf.float32)
ts1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [18]:
ts1=tf.cast(ts1,dtype=tf.float16)
ts1

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

Aggregating Tensors

In [20]:
k=tf.constant([[-7,10],[-10,7]])
k

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ -7,  10],
       [-10,   7]])>

In [21]:
tf.abs(k)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7]])>

In [23]:
tf.reduce_min(k)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [24]:
tf.reduce_max(k)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [25]:
i=tf.constant([[-11,-13],[14,15]])
i

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-11, -13],
       [ 14,  15]])>

In [27]:
tf.math.minimum(k,i)
#Returns the min of x and y (i.e. x < y ? x : y) element-wise.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-11, -13],
       [-10,   7]])>

In [28]:
tf.reduce_mean(k)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [29]:
tf.reduce_mean(i)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [32]:
tf.cast(k,tf.float16)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ -7.,  10.],
       [-10.,   7.]], dtype=float16)>

In [31]:
tf.math.reduce_variance(tf.cast(k,tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=74.5>

In [33]:
x = tf.constant([[1., 2.], [3.,  ]])
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [35]:
tf.reduce_mean(x)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [36]:
tf.math.reduce_std(x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.1180339>

In [34]:
tf.math.reduce_variance(x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.25>

Finding max and min number poisition in each row of tensor

In [39]:
tf.random.set_seed(10)
ts3=tf.random.uniform(shape=(3,3))
ts3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.644151  , 0.8082472 , 0.8976548 ],
       [0.6368902 , 0.6270969 , 0.9936013 ],
       [0.02359486, 0.03668392, 0.5860578 ]], dtype=float32)>

In [57]:
l=tf.argmax(ts3[0])
l

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [58]:
ts3[0][tf.argmax(ts3[0])]

<tf.Tensor: shape=(), dtype=float32, numpy=0.8976548>

In [60]:
ts3[2][tf.argmin(ts3[2])]

<tf.Tensor: shape=(), dtype=float32, numpy=0.023594856>

One-hot Encoded Tensors

In [65]:
some_list=[0,1,2,3]
tf.one_hot(some_list,depth=4)
#tf.cast(some_list,dtype=tf.float32)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>